import { renderIntlHeader, renderIntlFooter } from './components/intl-shell.js';
import { mountIntlWorkspace } from './home-workspace.intl.js';
import { rememberLocaleLinks } from './core/locale.js';
import { mountEcosystem } from './components/ecosystem.js';
import { renderSitesNav } from './components/aixuno-sites.js';
import './language-router.js';
document.querySelector('#site-header').innerHTML=renderIntlHeader();
document.querySelector('#site-header').insertAdjacentHTML('afterend',renderSitesNav(document.documentElement.lang.split('-')[0]));
document.querySelector('#site-footer').innerHTML=renderIntlFooter();
rememberLocaleLinks();
mountEcosystem(document.documentElement.lang.split('-')[0]);
mountIntlWorkspace({cards:document.querySelector('#mode-cards'),workspace:document.querySelector('#workspace')});
